name: Build and Publish to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Build the ASP.NET application
      run: dotnet build --configuration Release

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Publish Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: ./Dockerfile  # Path to your Dockerfile
        platforms: linux/amd64
        push: true
        tags: kobeschoeters/devops:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log out from Docker Hub
      run: docker logout
      
    - name: Run ASP.NET application
      run: dotnet run --project Vacation.csproj
      timeout-minutes: 7
